/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Piotr' at '20.04.15 20:58' with Gradle 2.3
 *
 * @author Piotr, @date 20.04.15 20:58
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
